kind = "web"
    previewPath = "/main-app/"
    title = "PRE-Atendimento V8 (alt)"
    version = "1.0.0"
    id = "artifacts/main-app"
    router = "path"

    [[integratedSkills]]
    name = "react-vite"
    version = "1.0.0"

    [[services]]
    name = "web"
    paths = [ "/main-app/" ]
    localPort = 5000

    [services.development]
    run = "pnpm --filter @workspace/main-app run dev"

    [services.production]
    run = "pnpm --filter @workspace/main-app run serve"

    [services.env]
    PORT = "5000"
    BASE_PATH = "/main-app/"
